# Generated by Django 3.1.8 on 2021-04-13 08:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(default='N/A', max_length=255)),
                ('linksIn', models.IntegerField(default=0)),
                ('linksOut', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BsInTsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bs', models.IntegerField(default=0)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('card', models.IntegerField(default=0)),
                ('led', models.IntegerField(default=0)),
                ('place', models.IntegerField(default=0)),
                ('tx', models.BooleanField()),
                ('plinth', models.IntegerField(default=0)),
                ('pair', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iprobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=30)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('card', models.CharField(choices=[('1', 'card1'), ('2', 'card2'), ('3', 'card3'), ('4', 'card4'), ('5', 'card5')], default='', max_length=5)),
                ('iprobe', models.CharField(choices=[('1', 'iprobe1'), ('2', 'iprobe2'), ('3', 'iprobe3'), ('4', 'iprobe4'), ('5', 'iprobe5'), ('6', 'iprobe6'), ('7', 'iprobe7')], default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('StreamDirection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stream_direction', to='base0.direction')),
                ('TsToBs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base0.bsintsm')),
                ('ts_0', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TS0', to='base0.timeslot')),
                ('ts_1', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TS1', to='base0.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='BsOutTsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bs', models.IntegerField(default=0)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('card', models.IntegerField(default=0)),
                ('led', models.IntegerField(default=0)),
                ('place', models.IntegerField(default=0)),
                ('tx', models.BooleanField()),
                ('plinth', models.IntegerField(default=0)),
                ('pair', models.IntegerField(default=0)),
                ('hw', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='aggregatorHW', to='base0.iprobe')),
            ],
        ),
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('provider', models.TextField(blank=True, max_length=100)),
                ('serial', models.TextField(blank=True, max_length=100)),
                ('inventar', models.TextField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('place', models.TextField(blank=True, max_length=255)),
                ('contact', models.TextField(blank=True, max_length=100)),
                ('person', models.TextField(blank=True, max_length=100)),
                ('info', models.TextField(blank=True, max_length=100)),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inCity', to='base0.city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregatorsType', to='base0.aggregatorstype')),
            ],
        ),
        migrations.CreateModel(
            name='LeftSide',
            fields=[
                ('title', models.CharField(default='n/a', max_length=30)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('BsTsmIn', models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='base0.bsintsm')),
                ('info', models.TextField(blank=True, max_length=100)),
                ('BsTsmOut', models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='base0.bsouttsm')),
                ('hw', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='aggregatorHW', to='base0.aggregator')),
            ],
        ),
    ]
