# Generated by Django 3.1.8 on 2021-04-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0006_leftside_bstsmout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftside',
            name='BsTsmOut',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='base0.bsouttsm'),
        ),
    ]
