# Generated by Django 3.1.8 on 2021-04-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0007_auto_20210413_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftside',
            name='BsTsmOut',
        ),
    ]
