# Generated by Django 3.1.8 on 2021-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0013_auto_20210413_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsouttsm',
            name='tsm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='bsouttsm',
            unique_together={('tsm', 'bs')},
        ),
    ]
