# Generated by Django 3.1.8 on 2021-04-13 12:26

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0014_auto_20210413_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=30)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from='title')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
