# Generated by Django 3.1.8 on 2021-04-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0018_auto_20210413_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeftSide',
        ),
    ]
