# Generated by Django 3.1.8 on 2021-04-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0019_delete_leftside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='StreamDirection',
            new_name='streamDirection',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='TsToBs',
            new_name='tsToBs',
        ),
    ]
