# Generated by Django 3.1.8 on 2021-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0021_auto_20210415_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='tx',
            field=models.CharField(choices=[('1', 'TX'), ('0', 'RX')], default='', max_length=8),
        ),
    ]
