# Generated by Django 3.1.8 on 2021-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base0', '0022_object_tx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='tsToBs',
            new_name='bs',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='ts_1',
            new_name='ts1',
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('tsm', 'bs', 'ts1')},
        ),
    ]
